[tool.poetry]
name = "rutertider"
version = "0.1.0"
description = "Avgangstider for Ruter"
authors = ["Martin Høy <marhoy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^1.1"
requests = "^2.22"

[tool.poetry.dev-dependencies]
pytest = "^5.1"
pytest-cov = "^2.7"
flake8 = "^3.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
