name: Docker Publish

on:
  push:
    # When a new version tag is pushed
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: marhoy/avgangstider
          tags: type=semver,pattern={{major}}.{{minor}}.{{patch}}

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.29"

      - name: Get version from setuptools_scm
        id: version-getter
        run: echo "VERSION=$(uv run --with setuptools_scm -m setuptools_scm)" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            VERSION=${{ steps.version-getter.outputs.VERSION }}
